version: "3"
services:
  back:
    image: back:latest

  gateway:
    image: nginx:latest
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../dist:/usr/share/nginx/www